package com.elTohamy.flushy.utils

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.elTohamy.flushy.R

@Composable
fun getTournamentName(id: Int, jsonName: String): String {
    return when (id) {
        Constants.FWC -> stringResource(id = R.string.fwc)
        Constants.FWC_Q_AF -> stringResource(id = R.string.fwc_q_af)
        Constants.FWC_Q_AS -> stringResource(id = R.string.fwc_q_as)
        Constants.FWC_Q_EU -> stringResource(id = R.string.fwc_q_eu)
        Constants.FWC_Q_CON -> stringResource(id = R.string.fwc_q_na)
        Constants.FWC_Q_OC -> stringResource(id = R.string.fwc_q_oc)
        Constants.FWC_Q_SA -> stringResource(id = R.string.fwc_q_sa)
        Constants.FWC_Q_PLAY_OFFS -> stringResource(id = R.string.fwc_q_po)
        Constants.FWC_W -> stringResource(id = R.string.fwc_w)
        Constants.EURO -> stringResource(id = R.string.euro)
        Constants.EURO_QUALIFIERS -> stringResource(id = R.string.euro_q)
        Constants.UNL -> stringResource(id = R.string.unl)
        Constants.AFCON -> stringResource(id = R.string.afcon)
        Constants.AFCON_Q -> stringResource(id = R.string.afcon_q)
        Constants.AFCON_U_23 -> stringResource(id = R.string.afcon_u23)
        Constants.AFRICAN_NATIONS_C -> stringResource(id = R.string.afn_ch)
        Constants.ASIAN_CUP -> stringResource(id = R.string.asian_cup)
        Constants.ASIAN_CUP_Q -> stringResource(id = R.string.asian_cup_q)
        Constants.CON_GOLD_CUP -> stringResource(id = R.string.gold_cup)
        Constants.COPA_AMERICA -> stringResource(id = R.string.copa_am)
        Constants.ARAB_CUP -> stringResource(id = R.string.arab_cup)
        Constants.INT_CH_CUP -> stringResource(id = R.string.international_ch_cup)
        Constants.UCL -> stringResource(id = R.string.ucl)
        Constants.UEL -> stringResource(id = R.string.uel)
        Constants.UEFA_CONF -> stringResource(id = R.string.uecl)
        Constants.UCL_W -> stringResource(id = R.string.ucl_w)
        Constants.UEFA_YOUTH -> stringResource(id = R.string.uyl)
        Constants.CAF_CL -> stringResource(id = R.string.ccl)
        Constants.CONFEDERATION -> stringResource(id = R.string.caf_cc)
        Constants.CAF_SUPER_CUP -> stringResource(id = R.string.caf_sc)
        Constants.CONMEBOL -> stringResource(id = R.string.con_sud)
        Constants.LIBERTADORES -> stringResource(id = R.string.lib)
        Constants.CON_CL -> stringResource(id = R.string.con_cl)
        Constants.AFC_CL -> stringResource(id = R.string.afc_cl)
        Constants.AFC_CUP -> stringResource(id = R.string.afc_cup)
        Constants.PREMIER_LEAGUE_ID -> stringResource(id = R.string.en_pl)
        Constants.FA_CUP -> stringResource(id = R.string.fa_cup)
        Constants.CHAMPIONSHIP -> stringResource(id = R.string.champ)
        Constants.EFL -> stringResource(id = R.string.efl)
        Constants.LEAGUE_CUP -> stringResource(id = R.string.league_cup)
        Constants.COMMUNITY_SHIELD -> stringResource(id = R.string.com_sh)
        Constants.LA_LIGA -> stringResource(id = R.string.la_liga)
        Constants.COPA_DEL_REY -> stringResource(id = R.string.copa_del)
        Constants.SUPER_CUP_SPAIN -> stringResource(id = R.string.spain_sc)
        Constants.SERIE_A -> stringResource(id = R.string.serie_a)
        Constants.COPPA_ITALIA -> stringResource(id = R.string.copa_it)
        Constants.SUPER_CUP_ITALY -> stringResource(id = R.string.italy_sc)
        Constants.BUNDESLIGA -> stringResource(id = R.string.bundes)
        Constants.DFB_POKAL -> stringResource(id = R.string.dfb_pokal)
        Constants.SUPER_CUP_GERMANY -> stringResource(id = R.string.german_sc)
        Constants.LIGUE_1 -> stringResource(id = R.string.ligue_1)
        Constants.COPPA_DE_LA_LIGUE -> stringResource(id = R.string.coppa_ligue)
        Constants.COUPE_DE_FRANCE -> stringResource(id = R.string.coupe_fr)
        Constants.PRIMEIRA_LIGA -> stringResource(id = R.string.pre_liga)
        Constants.TOCA_DE_LA_LIGA -> stringResource(id = R.string.toca_liga)
        Constants.SUPER_CUP_POR -> stringResource(id = R.string.por_sc)
        Constants.SUPER_LIG -> stringResource(id = R.string.tur_super_lig)
        Constants.CUP_TUR -> stringResource(id = R.string.tur_cup)
        Constants.SUPER_CUP_TUR -> stringResource(id = R.string.tur_sc)
        Constants.EREDIVISIE -> stringResource(id = R.string.eredivisie)
        Constants.JUPILER -> stringResource(id = R.string.jupiler)
        Constants.SERIE_A_BRA -> stringResource(id = R.string.bra_serie_a)
        Constants.COPA_DE_BRA -> stringResource(id = R.string.bra_cup)
        Constants.LIGA_ARG -> stringResource(id = R.string.arg_league)
        Constants.COPA_ARG -> stringResource(id = R.string.arg_cup)
        Constants.PRO_LEAGUE_SAU -> stringResource(id = R.string.roshan)
        Constants.KINGS_CUP -> stringResource(id = R.string.kings_cup)
        Constants.SUPER_CUP_SAU -> stringResource(id = R.string.sau_sc)
        Constants.PREMIER_LEAGUE_EGY -> stringResource(id = R.string.egy_pl)
        Constants.EGYPT_CUP -> stringResource(id = R.string.egy_cup)
        Constants.EGYPT_SUPER_CUP -> stringResource(id = R.string.egy_sc)
        Constants.LIGUE_1_TUN -> stringResource(id = R.string.tun_league)
        Constants.TUN_CUP -> stringResource(id = R.string.tun_cup)
        Constants.BOTOLA_PRO -> stringResource(id = R.string.botola)
        Constants.MOR_CUP -> stringResource(id = R.string.mor_cup)
        else -> jsonName
    }
}